In [13]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import StandardScaler

In [14]:

df=pd.read_csv("iris.csv")
X = df.iloc[:, [0,1,2,3]].values
Y = df.iloc[:, 4].values

In [15]:
#df.skew()


In [16]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_rescaled = data_scaler.fit_transform(X)
data_rescaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [17]:
binarizer = Binarizer(threshold=0.5).fit(X)
Data_binarized = binarizer.transform(X)
print("\nBinarty data:\n", Data_binarized[0:5])


Binarty data:
 [[1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]]


In [18]:
#standardscaler to convert scaled data with mean 0, SD =1
data = np.array([ [0,0],[1,0],[0,1],[1,1] ])
data_scaler = StandardScaler().fit(data)
data_rescaled = data_scaler.transform(data)
print(data_rescaled)

[[-1. -1.]
 [ 1. -1.]
 [-1.  1.]
 [ 1.  1.]]


In [21]:
#for every column , axis = 0
data_rescaled.mean(axis=0)


array([0., 0.])

In [22]:
data_rescaled.std(axis=0)

array([1., 1.])

In [25]:
#data = np.array(Data_binarized)
data_scaler = StandardScaler().fit(Data_binarized)
data_rescaled = data_scaler.transform(Data_binarized)
print(data_rescaled)

[[ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.         -1.43569652]
 [ 0.          0.          0.  